# Install the course conda environment with the following command:
# conda env create -f environment.yaml
# Once you install it, you should be able to see it in your Jupyter Lab. 
# If not, check the documentation here: https://ipython.readthedocs.io/en/stable/install/kernel_install.html
name: 'dsi-ml-workshop'
channels:
    - conda-forge
    - pytorch
    - anaconda
    - plotly
    - defaults    
dependencies:
    - python==3.12
    - ipykernel
    - matplotlib
    - pandas
    - scikit-learn>=1.5.1    
    - requests
    - ipython
    - graphviz
    - python-graphviz
    - jinja2
    - torchvision
    - torchaudio
    - pytorch
    - autograd
    - plotly
    - wikipedia    
    - spacy
    - nltk    
    - pip>=24.2        
    - pip:
        - mglearn
        - graphviz        
        - nbformat
        - nbclient
        - transformers
        - datasets
        - ultralytics
        - psutil>=5.7.2
