---
title: 'CPSC 330 Lecture 17: Recommendation systems'
description: "Unsupervised paradigm, motivation and potential applications of clustering, K-Means algorithm, pros and cons of K-Means, the Elbow plot and Silhouette plots for a given dataset,  importance of input data representation in clustering."
format:
    revealjs:
        html-math-method: plain
        slide-number: true
        slide-level: 2
        theme:
          - slides.scss
        center: true
        logo: img/UBC-CS-logo.png
        resources:
          - data/
          - img/

editor:
  render-on-save: true
---


## Announcements

- Homework 6 is due Wednesday, November 6th at 11:59pm. 
- No classes or OH during the midterm break.
- Midterm 2 coming up next week

## iClicker Exercise 

What percentage of watch time on YouTube do you think comes from recommendations?

- (A) 50%
- (B) 60%
- (C) 20%
- (D) 90%

This question is based on [this source](https://developers.google.com/machine-learning/recommendation/overview). The statistics might have changed now. 


# [Class demo](https://github.com/UBC-CS/cpsc330-2024W1/blob/main/lectures/102-Varada-lectures/class_demos/demo_17-recommendation-systems.ipynb)

## iClicker Exercise 17.1 {.smaller}
Select all of the following statements which are **True** 

- (A) In the context of recommendation systems, the shapes of validation utility matrix and train utility matrix are the same. 
- (B) RMSE perfectly captures what we want to measure in the context of recommendation systems. 
- (C) It would be reasonable to impute missing values in the utility matrix by taking the average of the ratings given to an item by similar users.  
- (D) In KNN type imputation, if a user has not rated any items yet, a reasonable strategy would be recommending them the most popular item. 


## iClicker Exercise 17.2 {.smaller}

Select all of the following statements which are **True**

(A) In content-based filtering we leverage available item features in addition to similarity between users.
(B) In content-based filtering you represent each user in terms of known features of items.
(C) In the set up of content-based filtering we discussed, if you have a new movie, you would have problems predicting ratings for that movie.
(D) In content-based filtering if a user has a number of ratings in the training utility matrix but does not have any ratings in the validation utility matrix then we won't be able to calculate RMSE for the validation utility matrix.

<br><br><br><br>
