---
title: 'CPSC 330 Lecture 12: Ensembles'
description: Random forsts, gradient boosting, averaging, stacking 

format:
    revealjs:
        html-math-method: plain
        slide-number: true
        slide-level: 2
        theme:
          - slides.scss
        center: true
        logo: img/UBC-CS-logo.png
        resources:
          - data/
          - img/

editor:
  render-on-save: true
---

## Announcements 

- Midterm 1
  - How was it? 
- HW4 grading is almost done. The grades will be released later this week. 
- HW5 is an open-ended project-type homework. Please ensure to start early.  

## iClicker Exercise 12.0

**iClicker cloud join link: https://join.iclicker.com/VYFJ**

Which of the following scenarios has worked effectively for you in the past?

- (A) Working independently on a project/assignment.
- (B) Working with like-minded people.
- (C) Teaming up with a diverse group offering varied perspectives and skills.

## Ensembles {.smaller}

- Key idea: Combine multiple trees to build stronger models.
- These kinds of models are extremely popular in industry and machine learning competitions.   
- We are going to cover how to use a few popular tree-based models:  
    - Random forests
    - Gradient boosted trees (very high level)
- We will also talk about two common ways to combine different models:  
    - Averaging
    - Stacking 

# [Ensembles class demo](https://github.com/UBC-CS/cpsc330-2024W1/blob/main/lectures/102-Varada-lectures/class_demos/demo_12-ensembles.ipynb)


 


